version: '3'
services:
  nodejs:
    image: node-ttt
    command: tail -f /dev/null
    volumes:
      - ./back/node:/app
    depends_on:
      - redis
  go:
    image: go-ttt
    command: tail -f /dev/null
    volumes:
      - ./back/go:/app
    depends_on:
      - redis
  kotlin:
    image: kotlin-ttt
    command: tail -f /dev/null
    volumes:
      - ./back/kotlin:/app
  swift:
    image: swift-ttt
    command: tail -f /dev/null
    volumes:
      - ./back/swift:/app
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  frontend:
      image: nginx:alpine
      volumes:
        - ./front:/usr/share/nginx/html
      ports:
        - 80:80
      depends_on:
        - nodejs
        - go
        - kotlin
        - swift