version: '3'
services:
  nodejs:
    image: node-ttt
    container_name: node-app
    command: npm start
    volumes:
      - ./back/node:/app
    ports:
      - "8081:8081"
    depends_on:
      - redis
  go:
    image: go-ttt
    container_name: go-app
    command: go run /app/app/app.go
    volumes:
      - ./back/go:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
  kotlin:
    image: kotlin-ttt
    container_name: kotlin-app
    # tail -f /dev/null
    # command: java -jar build/libs/tic-tac-toe-1.0.0.jar
    command: /app/gradlew run
    volumes:
      - ./back/kotlin:/app
    ports:
      - "8082:8082"
    depends_on:
      - redis
  swift:
    image: swift-ttt
    container_name: swift-app
    # command: tail -f /dev/null
    # bash -c "swift run && /app/.build/x86_64-unknown-linux-gnu/debug/swift-ttt"
    # command: /app/.build/x86_64-unknown-linux-gnu/debug/swift-ttt
    # command: swift run
    command: swift run
    volumes:
      - ./back/swift:/app
    ports:
      - "8083:8083"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  frontend:
      image: nginx:alpine
      container_name: htmx-app
      volumes:
        - ./front:/usr/share/nginx/html
      ports:
        - "80:80"
      depends_on:
        - nodejs
        - go
        - kotlin
        - swift