version: '3'
services:
  nodejs:
    image: node-ttt
    command: tail -f /dev/null
    volumes:
      - ./back/node:/app
    ports:
      - "8081:8081"
    depends_on:
      - redis
  go:
    image: go-ttt
    command: tail -f /dev/null
    volumes:
      - ./back/go:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
  kotlin:
    image: kotlin-ttt
    command: tail -f /dev/null
    volumes:
      - ./back/kotlin:/app
    ports:
      - "8082:8082"
    depends_on:
      - redis
  swift:
    image: swift-ttt
    command: tail -f /dev/null
    volumes:
      - ./back/swift:/app
    ports:
      - "8083:8083"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  frontend:
      image: nginx:alpine
      volumes:
        - ./front:/usr/share/nginx/html
      ports:
        - "80:80"
      depends_on:
        - nodejs
        - go
        - kotlin
        - swift