version: '3'
services:
  nodejs:
    image: node-ttt
    command: tail -f /dev/null
    volumes:
      - ./node:/app
  go:
    image: go-ttt
    command: tail -f /dev/null
    volumes:
      - ./go:/app
  kotlin:
    image: kotlin-ttt
    command: tail -f /dev/null
    volumes:
      - ./kotlin:/app
  swift:
    image: swift-ttt
    command: tail -f /dev/null
    volumes:
      - ./swift:/app